# Generated by Django 5.2.10 on 2026-01-13 12:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment_label', models.CharField(default='Neutral', max_length=20)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('sentiment_confidence', models.FloatField(default=0.0)),
                ('themes', models.JSONField(default=list)),
                ('tokens', models.JSONField(blank=True, default=list, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product_id'], name='feedback_fe_product_dcc1b2_idx'), models.Index(fields=['sentiment_label'], name='feedback_fe_sentime_9ed2d1_idx'), models.Index(fields=['created_at'], name='feedback_fe_created_84c297_idx')],
            },
        ),
    ]
