# Generated by Django 5.2.10 on 2026-01-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='sentiment_score',
        ),
    ]
